### ISSUE TITLE
Change log in text

### ISSUE THREAD

**Issue by BronsonQuick** [humanmade/delegated-oauth2#3]
As per Paul's [comment](https://dev.hmn.md/2018/08/27/docs-humanmade-com-login/comment-page-1/) we should change the [wording](https://github.com/humanmade/delegated-oauth2/blob/ab69b3f5555907a050e3066e1afc7bae745c1b48/inc/cookie/namespace.php#L21) from "Login with Delegated Auth" to something more user friendly such as "Log in with your HM Central account"

**Comment by rmccue** [comment]
Let's make sure this is configurable, as this plugin isn't just for HM Central. Looks like we're using constants for the URL config, so could use the same for the text; I wonder if both should be moved to options instead though.
